In [8]:
# N개 주식으로 만든 포트폴리오
# 각 주식에 대한 확률과 수익률은 난수로 대체

import numpy as np

numStocks  = 4  # 자산의 개수

# 호황, 평상, 불황 세가지 국면별로 자산을 생성
returns = np.random.randn(3, numStocks)
print("난수로 만드는 국면별 주식의 수익률 : \n", returns)

# 세 국면별 확률. 전체 합이 1이 되도록 함
prob = np.random.rand(3)
prob = prob/prob.sum()
print("\n각 경기 국면 별 확률 : \n", prob)

# 경기 국면별 확률과 수익률을 곱. 각 주식의 기대수익률
expectedReturns = np.matmul(prob.T, returns)
print("\n각 주식의 기대수익률 : \n", expectedReturns)

# 투자 비중. 총합이 0이 되도록 함
weights = np.random.rand(numStocks)
weights = weights/weights.sum()
print("\n투자 비중 : \n", weights)

# 투자 비중과 기대수익률을 곱해서 포트폴리오 기대수익률 계산
expectedReturnsofPortfolio = np.sum(weights*expectedReturns)
print("\n포트폴리오 기대수익률 : {:.2%}".format(expectedReturnsofPortfolio))

난수로 만드는 국면별 주식의 수익률 : 
 [[ 0.2074632  -0.47340985 -2.71857119 -0.01847597]
 [ 0.47174926  1.29761021 -0.77169606 -2.33976503]
 [ 0.85365517  0.70757133  0.11657723  0.28503925]]

각 경기 국면 별 확률 : 
 [0.34340439 0.35151164 0.30508398]

각 주식의 기대수익률 : 
 [ 0.49750564  0.50942274 -1.16926357 -0.74183845]

투자 비중 : 
 [0.05004707 0.38077417 0.37888104 0.19029772]

포트폴리오 기대수익률 : -36.53%


In [9]:
# 실제 데이터의 기대수익률 계산

import numpy as np
import pandas as pd
from pandas_datareader import data as web
import random

tickers = ["MMM", "ADBE", "AMD", "GOOGL", "GOOG", "AMZN"]

adjClose = pd.DataFrame()  # 수정주가를 담을 데이터프레임

for item in tickers:
    adjClose[item] = web.DataReader(item, data_source="yahoo", start="15-09-2018")["Adj Close"]

# pct_change : 데이터의 변화량을 % 로 계산해줌
dailySimpleReturns = adjClose.pct_change()

# 기대수익률 대신 일간수익률의 평균 계산
meanReturns = np.matrix(dailySimpleReturns.mean())

# 참고 : 1년중 영업일은 250일 정도이므로 일간수익률에 250을 곱해서 연간수익률 생성
annualReturns = dailySimpleReturns.mean()*250
print("종목별 연간수익률 :", annualReturns)

numAssets = len(tickers)

# 주식 갯수만큼 투자 비중 생성
weights = np.random.random(numAssets)
weights = weights / sum(weights)
print("종목별 투자 비중 :", weights)

# 기대수익률 계산
portReturnsExpected = np.sum(weights*meanReturns.T)
print("포트폴리오 기대수익률 :", portReturnsExpected)

종목별 연간수익률 : MMM     -0.023615
ADBE     0.211147
AMD      0.511828
GOOGL    0.283030
GOOG     0.285542
AMZN     0.195164
dtype: float64
종목별 투자 비중 : [0.20485281 0.15081205 0.26530895 0.13167828 0.15192992 0.09541798]
포트폴리오 기대수익률 : 0.0010482873030065577


In [10]:
# 실제 데이터로 n개의 주식이 담긴 포트폴리오 계산

import numpy as np
import pandas as pd
from pandas_datareader import data as web
import random

tickers = ["MMM", "ADBE", "AMD", "GOOGL", "GOOG", "AMZN"]
adjClose = pd.DataFrame()

for item in tickers:
    adjClose[item] = web.DataReader(item, data_source="yahoo", start="15-09-2018")["Adj Close"]
dailySimpleReturns = adjClose.pct_change()

weights = np.matrix(weights)

# cov : 공분산 계산
pcov = dailySimpleReturns.cov().values

# 분산 계산(리스크)
varp = weights*pcov*weights.T
print("포트폴리오 분산 :", varp)

포트폴리오 분산 : [[0.0003645]]
